"use client";

/**
 * Deterministic balance-scale visual. Renders the "before" state (both sides
 * of the equation as written) and, if a repair step is supplied, the "after"
 * state once the same operation has been applied to both pans — this is the
 * literal visual metaphor for "do the same operation to both sides."
 *
 * All numbers are passed in as props (derived deterministically from the
 * verified equation string, see select-visual.ts) — nothing here is
 * generated by a model.
 */
export interface BalanceStep {
  leftLabel: string;
  rightLabel: string;
  opLabel?: string; // e.g. "-7" shown beneath both pans
}

export function BalanceEquationVisual({
  steps,
  caption,
}: {
  steps: BalanceStep[];
  caption?: string;
}) {
  return (
    <div className="flex flex-col gap-4">
      <div className={`grid gap-4 ${steps.length > 1 ? "grid-cols-2" : "grid-cols-1"}`}>
        {steps.map((step, i) => (
          <Scale key={i} left={step.leftLabel} right={step.rightLabel} opLabel={step.opLabel} />
        ))}
      </div>
      {caption && <p className="text-center text-xs text-ink-soft">{caption}</p>}
    </div>
  );
}

function Scale({ left, right, opLabel }: { left: string; right: string; opLabel?: string }) {
  return (
    <div className="flex flex-col items-center">
      <svg viewBox="0 0 200 130" className="w-full max-w-[220px]">
        {/* fulcrum */}
        <polygon points="90,110 110,110 100,90" fill="#C3B4F7" />
        <rect x="98" y="30" width="4" height="60" fill="#A78BFA" rx="2" />
        {/* beam */}
        <rect x="20" y="26" width="160" height="4" rx="2" fill="#8B5CF6" />
        {/* left chain + pan */}
        <line x1="35" y1="30" x2="35" y2="50" stroke="#A78BFA" strokeWidth="2" />
        <line x1="55" y1="30" x2="55" y2="50" stroke="#A78BFA" strokeWidth="2" />
        <path d="M25 50 Q45 75 65 50 Z" fill="#EDE9FD" stroke="#A78BFA" strokeWidth="2" />
        {/* right chain + pan */}
        <line x1="145" y1="30" x2="145" y2="50" stroke="#FFB27A" strokeWidth="2" />
        <line x1="165" y1="30" x2="165" y2="50" stroke="#FFB27A" strokeWidth="2" />
        <path d="M135 50 Q155 75 175 50 Z" fill="#FFF6EF" stroke="#FFB27A" strokeWidth="2" />
        {/* labels */}
        <text x="45" y="66" textAnchor="middle" fontSize="13" fontWeight={700} fill="#151833">
          {left}
        </text>
        <text x="155" y="66" textAnchor="middle" fontSize="13" fontWeight={700} fill="#151833">
          {right}
        </text>
        {/* base */}
        <rect x="60" y="110" width="80" height="6" rx="3" fill="#D3D5E6" />
      </svg>
      {opLabel && (
        <span className="mt-1 rounded-pill bg-lavender-100 px-3 py-1 text-xs font-semibold text-lavender-600">
          {opLabel} on both sides
        </span>
      )}
    </div>
  );
}
