import type { GapClassificationResult } from "@/lib/ai/schemas/pipeline";
import type { VerifiedStep } from "./verify-and-find-divergence";
import { toLinearForm } from "@/lib/math/solve-step";
import { parseLinearEquation } from "@/lib/math/linear-parse";

/**
 * Classification for the non-algebraic domains, read off the verifier's own
 * note. The note is generated by deterministic code, so matching on it is
 * matching on a proof rather than on model prose.
 */
function classifyByDomain(
  divergence: VerifiedStep,
  availableConcepts: { slug: string; name: string }[],
  pick: (...preferred: string[]) => string
): GapClassificationResult | null {
  const note = divergence.verificationNote;

  if (divergence.domain === "chemical") {
    const changedFormula = /never the formula itself/.test(note);
    return {
      conceptSlug: changedFormula
        ? pick("balancing-equations", "chemical-equations")
        : pick("balancing-equations", "chemical-equations"),
      classification: changedFormula ? "formula-altered" : "unbalanced-equation",
      surfaceError: note,
      underlyingGap: changedFormula
        ? "Balancing is done with the numbers in front of a substance, not the subscripts inside it. Changing a subscript makes the count work by turning it into a different chemical."
        : "The equation still has different numbers of at least one element on each side, so atoms are being created or destroyed.",
      evidence: [{ stepOrder: divergence.order, note }],
      confidence: "medium",
    };
  }

  if (divergence.domain === "quantitative") {
    const isUnitProblem = /units don't match/i.test(note);
    return {
      conceptSlug: isUnitProblem
        ? pick("units-and-dimensions", "formula-substitution")
        : pick("formula-substitution", "units-and-dimensions", "equations"),
      classification: isUnitProblem ? "unit-mismatch" : "arithmetic-error",
      surfaceError: note,
      underlyingGap: isUnitProblem
        ? "The units changed to something that measures a different quantity, which means an operation was applied that the formula does not support."
        : "The substitution is right but the arithmetic that follows from it does not come out to the value written.",
      evidence: [{ stepOrder: divergence.order, note }],
      confidence: "medium",
    };
  }

  if (availableConcepts.length === 0) return null;
  return null;
}

/**
 * Deterministic gap classification.
 *
 * The verifier has already proved *where* the reasoning broke. This decides
 * *what kind* of break it was, by comparing the algebraic structure of the step
 * the student wrote against the step they should have written — no model in the
 * loop. It runs whenever Gemini is unavailable, and its confidence is reported
 * honestly: "medium" when the error has an unambiguous algebraic signature,
 * "low" when the shape only narrows it down.
 */
export function classifyGapOffline(params: {
  divergence: VerifiedStep;
  previousExpression: string;
  availableConcepts: { slug: string; name: string }[];
}): GapClassificationResult {
  const { divergence, previousExpression } = params;
  const corrected = divergence.correctedExpression;
  const has = (slug: string) => params.availableConcepts.some((c) => c.slug === slug);
  const pick = (...preferred: string[]) =>
    preferred.find(has) ?? params.availableConcepts[0]?.slug ?? "equations";

  // Chemistry and quantitative errors have their own signatures; the algebraic
  // analysis below only makes sense for algebra.
  if (divergence.verdict === "first_divergence" || divergence.verdict === "independent_error") {
    const domainResult = classifyByDomain(divergence, params.availableConcepts, pick);
    if (domainResult) return domainResult;
  }

  const written = toLinearForm(divergence.expression);
  const shouldBe = corrected ? toLinearForm(corrected) : null;
  const previous = toLinearForm(previousExpression);
  const prev = parseLinearEquation(previousExpression);

  let classification = "invalid-transformation";
  let conceptSlug = pick("equations", "algebra");
  let underlyingGap = "This step changes the solution set, so it cannot follow from the step above it.";
  let confidence: "high" | "medium" | "low" = "low";

  if (written && shouldBe) {
    const constantGap = written.k - shouldBe.k;
    // Compare against the step they came FROM, not the step they should have
    // reached: dividing one side only changes the coefficient relative to the
    // previous line while leaving the other side untouched.
    const coefficientChanged =
      previous !== null &&
      Math.abs(previous.m - written.m) > 1e-9 &&
      Math.abs(previous.k - written.k) < 1e-9;

    // The signature of a sign error: a term crossed the equals sign keeping the
    // sign it already had. Moving b correctly lands at c - b; repeating the sign
    // lands at c + b, so the two differ by exactly 2b. Nothing else produces
    // that gap, which is why this can be named with real confidence.
    const movedWithoutInverting =
      prev !== null &&
      prev.constant !== 0 &&
      Math.abs(Math.abs(constantGap) - 2 * Math.abs(prev.constant)) < 1e-6 &&
      !coefficientChanged;

    if (movedWithoutInverting) {
      classification = "sign-error";
      conceptSlug = pick("sign-handling", "inverse-operations", "equations");
      underlyingGap = `Moving ${prev.constantOp}${prev.constant} across the equals sign means applying its inverse to both sides. It was carried over with the sign it already had, so the two sides no longer describe the same value.`;
      confidence = "medium";
    } else if (coefficientChanged) {
      const dividedOneSideOnly = previous !== null && Math.abs(previous.k - written.k) < 1e-9;
      classification = "inverse-operation-misapplied";
      conceptSlug = pick("inverse-operations", "equations");
      underlyingGap = dividedOneSideOnly
        ? "The coefficient was divided out on one side but not the other. An operation has to reach both sides or the equation stops balancing."
        : "The coefficient on the variable changed in a way the operation doesn't justify.";
      confidence = "medium";
    } else if (Math.abs(constantGap) > 1e-9) {
      classification = "arithmetic-error";
      conceptSlug = pick("equations", "algebra");
      underlyingGap =
        "The move itself is the right one, but the arithmetic that produced the new value doesn't come out.";
      confidence = "medium";
    }
  }

  const surfaceError = corrected
    ? `Wrote "${divergence.expression}" where the step should read "${corrected}".`
    : `Wrote "${divergence.expression}", which isn't equivalent to "${previousExpression}".`;

  return {
    conceptSlug,
    classification,
    surfaceError,
    underlyingGap,
    evidence: [
      { stepOrder: divergence.order, note: divergence.verificationNote },
      ...(corrected
        ? [{ stepOrder: divergence.order, note: `Algebraically the step resolves to "${corrected}".` }]
        : []),
    ],
    confidence,
  };
}
