import { Sparkles, Calculator } from "lucide-react";
import { cn } from "@/lib/cn";

/**
 * Says what produced a piece of content.
 *
 * A student should never have to wonder whether the thing in front of them came
 * from a language model or from algebra, and a reviewer should be able to tell
 * at a glance. Both labels are equally legitimate — this is provenance, not an
 * apology.
 */
export function SourceBadge({
  source,
  className,
}: {
  source: "gemini" | "deterministic";
  className?: string;
}) {
  const isAi = source === "gemini";
  const Icon = isAi ? Sparkles : Calculator;

  return (
    <span
      title={
        isAi
          ? "Generated by Gemini, then solved independently to confirm its answer is correct."
          : "Built and solved locally by GapFinder's own algebra — no model involved."
      }
      className={cn(
        "inline-flex shrink-0 items-center gap-1 rounded-pill px-2 py-0.5 text-[10px] font-semibold",
        isAi ? "bg-lavender-50 text-lavender-600" : "bg-navy-50 text-ink-soft",
        className
      )}
    >
      <Icon className="h-3 w-3" />
      {isAi ? "AI · verified" : "Verified locally"}
    </span>
  );
}
